version: '2'
services:
  nginx:
    image: 'nginx:1.9-alpine'
    networks:
    - fpm
    volumes:
      - upload:/var/www/upload/upload:ro
      - ${PWD}/website/web:/var/www/html:ro
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf:ro 
    ports:
      - 80:80
    links:
      - fpm
  fpm:
    build: 
      context: .
      dockerfile: Dockerfile_php
    networks:
    - fpm
    - db
    volumes:
      - upload:/var/www/upload
      - ${PWD}/website:/var/www/php
      - ${PWD}/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/php
    user: www-data
    links:
      - mariadb
  mariadb:
    image: mariadb:10.1.19
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - db:/var/lib/mysql
    networks:
      - db
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
  adminer:
    image: adminer
    ports:
    - 8080:8080
    networks:
     - db
networks:
  fpm:
    driver: bridge
  db:
    driver: bridge
volumes:
  db:
    driver: local
  upload:
    driver: local
